name: Build Vibestick

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build app
      run: |
        ./build_app.sh
    
    - name: Create DMG
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Create a simple DMG
        hdiutil create -volname "Vibestick" -srcfolder dist/Vibestick.app -ov -format UDZO Vibestick.dmg
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Vibestick-macOS
        path: dist/Vibestick.app
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Vibestick.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}